# example = "кораблекрушение"
# print("наше слово - ", example)
# print(example[0])
# print(example[-1])
# print(example[7:])
# print(example[::-1])
# print(example[1::2])
my_string = input("введите люой текст :" )
print( len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])

